-include_lib("nitrogen_core/include/wf.hrl").
-record(collapsiblelist, {?ELEMENT_BASE(element_collapsiblelist), numbered = false, collapsed = false, body=[]}).
-record(process_table, {?ELEMENT_BASE(element_process_table), data=[], body=[]}).
